import os
import sys
import joblib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from config import CLASSIFIER_PATH


def get_training_data():
    product_search = [
        "find iPhone 15 Pro price",
        "buy Samsung Galaxy S24",
        "where to get MacBook Air M2",
        "show me Dell XPS 13 deals",
        "Sony WH-1000XM5 buy online Pakistan",
        "get me a PS5 console",
        "Samsung QLED TV price in Pakistan",
        "OnePlus 12 availability",
        "iPad Air M1 cheapest price",
        "Logitech MX Master 3 buy",
        "search for wireless earbuds under 5000",
        "find me a good gaming laptop",
        "looking for a budget smartphone",
        "buy iPhone 14 Pro Max",
        "Samsung Galaxy Z Fold price",
        "MacBook Pro M3 buy Pakistan",
        "Dell monitor 27 inch price",
        "Sony camera A7IV buy",
        "Logitech keyboard wireless",
        "HP Pavilion laptop price",
        "Oppo Reno 10 buy",
        "Vivo V29 price Pakistan",
        "Xiaomi 14 Ultra buy",
        "Google Pixel 8 price",
        "Nothing Phone 2 buy",
        "AirPods Pro 2 price",
        "JBL speaker buy Pakistan",
        "Bose QuietComfort buy",
        "Lenovo ThinkPad price",
        "ASUS ROG laptop buy",
        "Razer Blade buy Pakistan",
        "Nikon camera buy",
        "Canon EOS R6 price",
        "GoPro Hero 12 buy",
        "Apple Watch Ultra buy",
        "Samsung Galaxy Watch buy",
        "Garmin watch price",
        "Fitbit Versa buy Pakistan",
        "Kindle Paperwhite buy",
        "Nintendo Switch buy",
        "Xbox Series X price",
        "Steam Deck buy Pakistan",
        "WD SSD 1TB buy",
        "Seagate hard drive price",
        "Corsair RAM buy",
        "Gigabyte motherboard price",
        "MSI laptop buy Pakistan",
        "Acer Predator buy",
        "Huawei Mate 60 buy",
        "Realme GT buy Pakistan",
        "Infinix Hot 40 price",
        "Tecno Spark price Pakistan",
        "where can I buy air conditioner",
        "best price for washing machine",
        "refrigerator price Pakistan",
        "microwave oven buy",
        "vacuum cleaner best price",
        "iron price Pakistan buy",
        "blender buy online",
        "coffee maker price",
        "water purifier buy Pakistan",
        "ceiling fan best price",
        "LED bulb price Pakistan",
        "power bank 20000mAh buy",
        "USB-C cable buy Pakistan",
        "wireless charger buy",
        "screen protector iPhone 15",
        "phone case Samsung S24",
        "laptop bag buy Pakistan",
        "webcam price buy",
        "microphone for recording buy",
        "headset for gaming buy",
        "smart watch buy Pakistan",
        "VR headset buy",
        "drone buy Pakistan price",
        "projector price buy",
        "printer HP buy Pakistan",
        "scanner price buy",
        "router WiFi buy",
        "mesh WiFi system buy",
        "external hard drive buy",
        "graphics card RTX 4070 buy",
        "processor AMD Ryzen buy",
        "Intel i9 price Pakistan",
        "power supply buy Pakistan",
        "CPU cooler buy",
        "PC case buy Pakistan",
        "gaming chair buy",
        "standing desk buy Pakistan",
        "monitor arm buy",
        "HDMI cable buy Pakistan",
        "ethernet cable buy",
        "network switch buy",
        "UPS price Pakistan buy",
        "solar panel buy Pakistan",
        "inverter price buy",
        "battery price Pakistan",
        "generator buy Pakistan",
        "water heater buy",
        "air purifier buy Pakistan",
        "dehumidifier buy",
        "space heater buy Pakistan",
        "electric kettle buy",
        "toaster buy Pakistan",
        "rice cooker buy",
        "food processor buy",
    ]

    price_comparison = [
        "compare iPhone 15 Pro prices across platforms",
        "which is cheaper Samsung S24 or iPhone 15",
        "price difference between MacBook Air and Dell XPS",
        "best price for PS5 in Pakistan",
        "compare Sony headphones prices",
        "which platform has cheapest iPad",
        "Samsung TV price comparison Daraz vs Telemart",
        "who sells OnePlus 12 cheaper",
        "compare laptop prices 2024",
        "best deal on wireless earbuds",
        "price comparison gaming monitors",
        "cheapest place to buy AirPods",
        "compare prices for Sony camera",
        "which shop has best price for Logitech mouse",
        "compare SSD prices across stores",
        "find cheapest graphics card",
        "price difference Samsung vs Apple",
        "budget phone comparison under 30000",
        "best price for gaming laptop 2024",
        "compare printer prices HP vs Canon",
        "which platform offers best discount",
        "cheapest PS5 bundle Pakistan",
        "compare smartwatch prices",
        "headphone price comparison Sony vs Bose",
        "laptop price range comparison",
        "compare TV prices 55 inch",
        "best value smartphone under 50000",
        "compare SSD 1TB prices",
        "cheapest wireless keyboard buy",
        "price comparison for monitors",
        "which store has cheapest Apple products",
        "compare projector prices",
        "best price for gaming mouse",
        "camera price comparison Canon vs Sony",
        "compare blender prices Pakistan",
        "cheapest router WiFi Pakistan",
        "compare headphone prices under 10000",
        "best deal for air conditioner",
        "compare prices for washing machine",
        "which platform has flash sale",
        "compare Samsung TV prices 2024",
        "cheapest place for Dell laptop",
        "compare iPhone prices different stores",
        "price comparison Bose vs Sony headphones",
        "find best deal on MacBook",
        "compare gaming console prices",
        "cheapest SSD brand comparison",
        "compare power bank prices",
        "best price for robot vacuum",
        "compare printer ink prices",
        "price difference gaming vs regular laptop",
        "cheapest smart home devices",
        "compare security camera prices",
        "best deal on espresso machine",
        "compare fitness tracker prices",
        "cheapest wireless earbuds 2024",
        "compare tablet prices iPad vs Samsung",
        "best price for 4K monitor",
        "compare home theater prices",
        "cheapest mechanical keyboard",
        "compare drone prices Pakistan",
        "best deal on standing desk",
        "compare microwave oven prices",
        "cheapest solar panel kit",
        "compare water purifier prices",
        "best price for electric scooter",
        "compare gaming headset prices",
        "cheapest WiFi extender",
        "compare action camera prices",
        "best deal on smart TV",
        "compare electric kettle prices",
        "cheapest laptop stand",
        "compare NAS storage prices",
        "best price for webcam 2024",
        "compare gaming controller prices",
        "cheapest portable speaker",
        "compare home security system prices",
        "best deal on espresso machine Pakistan",
        "compare air fryer prices",
        "cheapest graphics card 2024",
        "compare monitor arm prices",
        "best price for noise cancelling headphones",
        "compare USB hub prices",
        "cheapest digital clock buy",
        "compare ring light prices",
        "best deal on portable charger",
        "compare keyboard switch prices",
        "cheapest mouse pad gaming",
        "compare laptop cooling pad prices",
        "best price for smart plug",
        "compare ethernet switch prices",
        "cheapest cable management buy",
        "compare desk lamp prices",
        "best deal on bookshelf speakers",
    ]

    category_browse = [
        "show me all smartphones",
        "list available laptops",
        "browse gaming accessories",
        "what headphones are available",
        "show all tablets in stock",
        "list all Samsung products",
        "browse Apple products",
        "show me all TVs under 200000",
        "list gaming consoles available",
        "browse cameras and lenses",
        "show all audio products",
        "list all accessories under 5000",
        "browse computer components",
        "show me all smartwatches",
        "list home appliances available",
        "show all networking equipment",
        "browse storage devices",
        "list all printers available",
        "show me kitchen appliances",
        "browse fitness equipment",
        "show all monitors available",
        "list power and charging products",
        "browse smart home devices",
        "show me all brands",
        "list products on sale",
        "show all new arrivals",
        "browse budget phones under 30000",
        "list all wireless devices",
        "show me cleaning appliances",
        "browse entertainment products",
        "show all cooling products",
        "list audio accessories",
        "show me all gaming gear",
        "browse professional equipment",
        "list all cables and adapters",
        "show all camera accessories",
        "browse outdoor electronics",
        "show me all inverter products",
        "list all LED lights available",
        "show all security products",
        "browse medical devices",
        "show me all kitchen gadgets",
        "list all travel accessories",
        "show all office equipment",
        "browse all mobile accessories",
        "show me all robot cleaners",
        "list all projector options",
        "show all water products",
        "browse all pet electronics",
        "show me all solar products",
        "list all emergency products",
    ]

    deal_alert = [
        "any flash sale today",
        "show me today's deals",
        "what discounts are available",
        "find coupon codes for Daraz",
        "best deals running right now",
        "flash sale on smartphones",
        "any offer on iPhone today",
        "discount on Samsung products",
        "weekend sale deals Pakistan",
        "Ramadan sale offers",
        "11.11 sale deals",
        "Black Friday deals Pakistan",
        "Independence Day sale",
        "Eid sale offers electronics",
        "clearance sale items",
        "any promo code available",
        "special discount for students",
        "bank discount offers",
        "free shipping deals",
        "bundle offers on electronics",
        "trade-in deals smartphones",
        "exchange offer iPhone",
        "cashback offers Pakistan",
        "installment plans available",
        "0% interest installment",
        "buy now pay later deals",
        "limited time offer electronics",
        "doorbuster deals today",
        "lightning deal available",
        "today only discount",
        "sale ending soon",
        "last chance to buy",
        "exclusive online discount",
        "member only deals",
        "VIP sale access",
        "early bird discount",
        "first purchase discount",
        "newsletter signup discount",
        "refurbished deals",
        "open box deals Pakistan",
        "warehouse sale electronics",
        "factory outlet deals",
        "seasonal clearance Pakistan",
        "mid year sale 2026",
        "end of season sale",
        "monsoon sale deals",
        "winter sale electronics",
        "summer sale Pakistan",
        "back to school deals",
        "new year sale offers",
        "valentine day deals",
        "workers day sale",
        "quaid day sale Pakistan",
        "billion day sale Daraz",
        "mega sale event",
        "super sale Pakistan",
        "grand sale electronics",
        "mystery discount deals",
        "spin the wheel discount",
        "scratch card deals",
        "lucky draw electronics",
        "giveaway deals Pakistan",
        "contest winner deals",
        "social media exclusive",
        "app only deals",
        "mobile app discount",
        "first app order discount",
        "refer a friend deal",
        "loyalty points redemption",
        "reward program deals",
        "gold member deals",
        "silver member discount",
        "bronze member offer",
        "new customer discount",
        "returning customer offer",
        "birthday month discount",
        "anniversary sale deals",
        "clearance before new models",
        "old model clearance",
        "end of line sale",
        "sample sale electronics",
        "display unit sale",
        "test unit deals",
        "open package deals",
        "missing accessory deals",
        "cosmetic damage discount",
        "scratch and dent sale",
        "imperfect box deals",
        "expired warranty deals",
        "extended warranty offers",
        "free accessory bundle",
        "gift with purchase",
        "buy one get one deals",
        "cash on delivery discount",
        "prepayment discount",
        "bank transfer offer",
        "wallet cashback deals",
    ]

    texts = product_search + price_comparison + category_browse + deal_alert
    labels = (
        ["product_search"] * len(product_search)
        + ["price_comparison"] * len(price_comparison)
        + ["category_browse"] * len(category_browse)
        + ["deal_alert"] * len(deal_alert)
    )
    return texts, labels


def train():
    os.makedirs(os.path.dirname(CLASSIFIER_PATH), exist_ok=True)
    texts, labels = get_training_data()

    vectorizer = TfidfVectorizer(
        max_features=5000,
        ngram_range=(1, 2),
        stop_words="english"
    )
    X = vectorizer.fit_transform(texts)

    model = LinearSVC(C=1.0, max_iter=1000)
    model.fit(X, labels)

    joblib.dump({"vectorizer": vectorizer, "model": model}, CLASSIFIER_PATH)
    print(f"Classifier trained and saved to {CLASSIFIER_PATH}")
    print(f"Training samples: {len(texts)}")
    print(f"Labels: {set(labels)}")


if __name__ == "__main__":
    train()
